generator:
  class: sfDoctrineGenerator
  param:
    model_class:           aFormSubmission
    theme:                 aFormSubmissionAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          a_form_submission_admin
    with_doctrine_route:   1
    # body_class: some-body-class # TODO: Make this work! # make theme name a body class
    
    config:
      list:
        display: [ created_at ] 
        # display: [ id, ip_address, user_id ]
        object_actions: ~
        actions:
          _new: ~
          _export: ~
      form:
        class: aFormBuilder
      filter:
        class: aFormBuilderFilter
        display: [ user_id ]
      actions:
        _export: { label: "Export" }
