a_form:
  class: sfDoctrineRouteCollection
  options:
    model:                aForm
    module:               aForm
    prefix_path:          admin/a_form
    column:               id
    with_wildcard_routes: true
    object_actions:
      showLayout:    get
      addLayout:     post
      updateLayout:  put
      editLayout:    [get, post]
      deleteLayout:  post
      sortLayouts:   post
      showLayoutOption:    get
      addLayoutOption:     post
      updateLayoutOption:  put
      editLayoutOption:    [get, post]
      deleteLayoutOption:  post
      sortLayoutOptions:   post

a_form_submission:
  url:      /admin/a_form_submission
  param:    { module: aFormSubmission, action: index }
  requirements:
    sf_method: [ get ]

a_form_submission_new:
  url:      /admin/a_form_submission/new/:id
  class:    sfDoctrineRoute
  options:  { model: aForm, type: object }
  param:    { module: aFormSubmission, action: new }
  requirements:
    id: \d+
    sf_method: [ get ]
    
a_form_submission_create:
  url:      /admin/a_form_submission/create/:id
  class:    sfDoctrineRoute
  options:  { model: aForm, type: object }
  param:    { module: aFormSubmission, action: create }
  requirements:
    id: \d+
    sf_method: [ post ]
    
a_form_submission_edit:
  url:      /admin/a_form_submission/edit/:id
  class:    sfDoctrineRoute
  options:  { model: aFormSubmission, type: object }
  param:    { module: aFormSubmission, action: edit }
  requirements:
    id: \d+
    sf_method: [ get ]
    
a_form_submission_update:
  url:      /admin/a_form_submission/update/:id
  class:    sfDoctrineRoute
  options:  { model: aFormSubmission, type: object }
  param:    { module: aFormSubmission, action: update }
  requirements:
    id: \d+
    sf_method: [ post ]

a_form_submission_secuence_new:
  url:      /admin/a_form_submission/secuence_new/:form_id
  class:    sfRoute
  param:    { module: aFormSubmission, action: newSequence }
  requirements:
    form_id: \d+
    sf_method: get

a_form_submission_sequence:
  url:      /admin/a_form_submission/secuence/:id/:form_id/:layout_rank
  class:    sfDoctrineRoute
  options:  { model: aFormSubmission, type: object }
  param:    { module: aFormSubmission, action: sequence }
  requirements:
    id: \d+
    form_id: \d+
    layout_rank: \d+
    sf_method: get 
    
a_form_submission_sequence_submit:
  url:      /admin/a_form_submission/secuence_submit/:id/:form_id/:layout_id
  class:    sfDoctrineRoute
  options:  { model: aFormSubmission, type: object }
  param:    { module: aFormSubmission, action: sequence }
  requirements:
    id: \d+
    form_id: \d+
    layout_id: \d+
    sf_method: post
    
a_form_submission_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               aFormSubmission
    module:              aFormSubmissionAdmin
    prefix_path:         admin/a_form_submission_admin
    column:              id
    with_wildcard_routes: true
    collection_actions:
      export: [ get ]
    