a_form:
  class: sfDoctrineRouteCollection
  options:
    model:                aForm
    module:               aForm
    prefix_path:          admin/a_form
    column:               id
    with_wildcard_routes: true
    object_actions:
      showFieldset:    get
      addFieldset:     post
      updateFieldset:  put
      editFieldset:    [get, post]
      deleteFieldset:  post
      sortFieldsets:   post
      showFieldsetOption:    get
      addFieldsetOption:     post
      updateFieldsetOption:  [post, put]
      editFieldsetOption:    [get, post]
      deleteFieldsetOption:  post
      sortFieldsetOptions:   post
      index: get

a_form_submission:
  url:      /admin/a_form_submission
  param:    { module: aFormSubmission, action: index }
  requirements:
    sf_method: [ get ]

a_form_submission_new:
  url:      /admin/a_form_submission/new/:id
  class:    sfDoctrineRoute
  options:  { model: aForm, type: object }
  param:    { module: aFormSubmission, action: new }
  requirements:
    id: \d+
    sf_method: [ get ]
    
a_form_submission_create:
  url:      /admin/a_form_submission/create/:id
  class:    sfDoctrineRoute
  options:  { model: aForm, type: object }
  param:    { module: aFormSubmission, action: create }
  requirements:
    id: \d+
    sf_method: [ post ]
    
a_form_submission_edit:
  url:      /admin/a_form_submission/edit/:id
  class:    sfDoctrineRoute
  options:  { model: aFormSubmission, type: object }
  param:    { module: aFormSubmission, action: edit }
  requirements:
    id: \d+
    sf_method: [ get ]
    
a_form_submission_update:
  url:      /admin/a_form_submission/update/:id
  class:    sfDoctrineRoute
  options:  { model: aFormSubmission, type: object }
  param:    { module: aFormSubmission, action: update }
  requirements:
    id: \d+
    sf_method: [ post ]

a_form_submission_sequence_new:
  url:      /admin/a_form_submission/sequence_new/:id
  class:    sfDoctrineRoute
  options:  { model: aForm, type: object }
  param:    { module: aFormSubmission, action: newSequence }
  requirements:
    id: \d+
    sf_method: get

a_form_submission_sequence:
  url:      /admin/a_form_submission/sequence/:id/:form_id/:fieldset_rank
  class:    sfDoctrineRoute
  options:  { model: aFormSubmission, type: object }
  param:    { module: aFormSubmission, action: sequence }
  requirements:
    id: \d+
    form_id: \d+
    fieldset_rank: \d+
    sf_method: [ get, post ] 
    
a_form_submission_sequence_submit:
  url:      /admin/a_form_submission/sequence_submit/:id/:form_id/:fieldset_id
  class:    sfDoctrineRoute
  options:  { model: aFormSubmission, type: object }
  param:    { module: aFormSubmission, action: sequence }
  requirements:
    id: \d+
    form_id: \d+
    fieldset_id: \d+
    sf_method: post
    
a_form_submission_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               aFormSubmission
    module:              aFormSubmissionAdmin
    prefix_path:         admin/a_form_submission_admin
    column:              id
    with_wildcard_routes: true
    collection_actions:
      export: [ get ]
    